### ISSUE TITLE
Non-Milk liquids fail to preprocess

### ISSUE THREAD

**Issue by asher-k** [asher-k/MilkRA#5]
Current preprocessing script assumes droplet width & position is static. While true for milk droplets, water and other liquids experience movements and contractions on smoother surfaces, leading to incorrect measurement positions. 

Script should be tuned to allow for dynamic measurement locations based on the midpoint and variable distances between observations based on the width.

**Comment by VeryEager** [comment]
Per Gideon's advice we'll hold off on adapting the script for water droplets until more water samples can be collected.
