### ISSUE TITLE
preprocessing/script.py is outdated

### ISSUE THREAD

**Issue by asher-k** [asher-k/MilkRA#7]
Multi-sequence processing functions in `script.py` require refactoring according to the new methodology in [9be0010](https://github.com/VeryEager/MilkRA/commit/9be0010ea8fffc2ae976978c3db739c4b9cce716).

**Comment by VeryEager** [comment]
Changed priority to low for the time as `script.py` does not see as much activity compared to `preprocess.py`

**Comment by VeryEager** [comment]
Caution: processed data is now also stored in `data/`, need to update loading path to avoid the subdirectory.https://mail.google.com/mail/u/0/#inbox

**Comment by asher-k** [comment]
Closing as script is deprecated and no longer needed/preferred over the single-run option.
